<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250129073952 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE medicament_prescrit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dose VARCHAR(100) NOT NULL, frequence VARCHAR(255) NOT NULL, prescription_id INT NOT NULL, medicament_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2640BAB993DB413D ON medicament_prescrit (prescription_id)');
        $this->addSql('CREATE INDEX IDX_2640BAB9AB0D61F7 ON medicament_prescrit (medicament_id)');
        $this->addSql('ALTER TABLE medicament_prescrit ADD CONSTRAINT FK_2640BAB993DB413D FOREIGN KEY (prescription_id) REFERENCES prescription_medicaments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medicament_prescrit ADD CONSTRAINT FK_2640BAB9AB0D61F7 FOREIGN KEY (medicament_id) REFERENCES pharmacie (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prescription_medicaments DROP CONSTRAINT fk_abfcf59aab0d61f7');
        $this->addSql('DROP INDEX idx_abfcf59aab0d61f7');
        $this->addSql('ALTER TABLE prescription_medicaments DROP dose');
        $this->addSql('ALTER TABLE prescription_medicaments DROP frequence');
        $this->addSql('ALTER TABLE prescription_medicaments DROP medicament_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE medicament_prescrit DROP CONSTRAINT FK_2640BAB993DB413D');
        $this->addSql('ALTER TABLE medicament_prescrit DROP CONSTRAINT FK_2640BAB9AB0D61F7');
        $this->addSql('DROP TABLE medicament_prescrit');
        $this->addSql('ALTER TABLE prescription_medicaments ADD dose VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE prescription_medicaments ADD frequence VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE prescription_medicaments ADD medicament_id INT NOT NULL');
        $this->addSql('ALTER TABLE prescription_medicaments ADD CONSTRAINT fk_abfcf59aab0d61f7 FOREIGN KEY (medicament_id) REFERENCES pharmacie (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_abfcf59aab0d61f7 ON prescription_medicaments (medicament_id)');
    }
}
