<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250401220219 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE bebe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, date_naissance TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sexe VARCHAR(255) NOT NULL, numero_dossier VARCHAR(255) DEFAULT NULL, mere_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_946475AD39DEC40E ON bebe (mere_id)');
        $this->addSql('CREATE TABLE biologie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_examen VARCHAR(100) NOT NULL, resultat TEXT DEFAULT NULL, date_examen TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commentaires TEXT DEFAULT NULL, statut VARCHAR(100) NOT NULL, patient_id INT NOT NULL, technicien_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EB9829936B899279 ON biologie (patient_id)');
        $this->addSql('CREATE INDEX IDX_EB98299313457256 ON biologie (technicien_id)');
        $this->addSql('CREATE TABLE consultation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_consultation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, diagnostique TEXT DEFAULT NULL, traitement TEXT DEFAULT NULL, patient_id INT NOT NULL, medecin_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_964685A66B899279 ON consultation (patient_id)');
        $this->addSql('CREATE INDEX IDX_964685A64F31A84 ON consultation (medecin_id)');
        $this->addSql('CREATE TABLE gynecologie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_consultation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, diagnostic TEXT NOT NULL, plan_traitement TEXT DEFAULT NULL, date_suivi TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patient_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AC9A669E6B899279 ON gynecologie (patient_id)');
        $this->addSql('CREATE TABLE hospitalisation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_entree TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_sortie TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, chambre VARCHAR(10) NOT NULL, remarques TEXT DEFAULT NULL, patient_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_67C059596B899279 ON hospitalisation (patient_id)');
        $this->addSql('CREATE TABLE maternite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_accouchement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type_accouchement VARCHAR(255) NOT NULL, notes TEXT DEFAULT NULL, mere_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7E1C52BC39DEC40E ON maternite (mere_id)');
        $this->addSql('CREATE TABLE maternite_bebe (maternite_id INT NOT NULL, bebe_id INT NOT NULL, PRIMARY KEY(maternite_id, bebe_id))');
        $this->addSql('CREATE INDEX IDX_D9F229E63689A1A3 ON maternite_bebe (maternite_id)');
        $this->addSql('CREATE INDEX IDX_D9F229E6AF762365 ON maternite_bebe (bebe_id)');
        $this->addSql('CREATE TABLE medecin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, telephone VARCHAR(15) NOT NULL, email VARCHAR(100) NOT NULL, adresse TEXT NOT NULL, specialite VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE medicament_prescrit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dose VARCHAR(100) NOT NULL, frequence VARCHAR(255) NOT NULL, prescription_id INT NOT NULL, medicament_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2640BAB993DB413D ON medicament_prescrit (prescription_id)');
        $this->addSql('CREATE INDEX IDX_2640BAB9AB0D61F7 ON medicament_prescrit (medicament_id)');
        $this->addSql('CREATE TABLE patient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, date_naissance DATE NOT NULL, adresse TEXT NOT NULL, telephone VARCHAR(15) NOT NULL, num_secu_social VARCHAR(50) NOT NULL, sexe VARCHAR(10) NOT NULL, date_enregistrement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pharmacie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, medicament VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, stock INT NOT NULL, date_peremption DATE NOT NULL, numero_lot VARCHAR(255) DEFAULT NULL, emplacement VARCHAR(150) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE prescription_medicaments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_prescription DATE NOT NULL, patient_id INT NOT NULL, prescripteur_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ABFCF59A6B899279 ON prescription_medicaments (patient_id)');
        $this->addSql('CREATE INDEX IDX_ABFCF59AD486E642 ON prescription_medicaments (prescripteur_id)');
        $this->addSql('CREATE TABLE radiologie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_examen VARCHAR(255) NOT NULL, date_examen TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resultat TEXT DEFAULT NULL, images TEXT DEFAULT NULL, patient_id INT NOT NULL, technicien_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_12FB57496B899279 ON radiologie (patient_id)');
        $this->addSql('CREATE INDEX IDX_12FB574913457256 ON radiologie (technicien_id)');
        $this->addSql('CREATE TABLE rendez_vous (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_rendezvous TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(20) NOT NULL, patient_id INT NOT NULL, medecin_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_65E8AA0A6B899279 ON rendez_vous (patient_id)');
        $this->addSql('CREATE INDEX IDX_65E8AA0A4F31A84 ON rendez_vous (medecin_id)');
        $this->addSql('CREATE TABLE urgence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, heure_arrivee TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, etape_actuelle VARCHAR(255) NOT NULL, etape_suivante VARCHAR(255) DEFAULT NULL, statut VARCHAR(255) NOT NULL, heure_sortie TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patient_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_737D6BCD6B899279 ON urgence (patient_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email TEXT NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, password TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE bebe ADD CONSTRAINT FK_946475AD39DEC40E FOREIGN KEY (mere_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE biologie ADD CONSTRAINT FK_EB9829936B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE biologie ADD CONSTRAINT FK_EB98299313457256 FOREIGN KEY (technicien_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A66B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A64F31A84 FOREIGN KEY (medecin_id) REFERENCES medecin (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gynecologie ADD CONSTRAINT FK_AC9A669E6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hospitalisation ADD CONSTRAINT FK_67C059596B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE maternite ADD CONSTRAINT FK_7E1C52BC39DEC40E FOREIGN KEY (mere_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE maternite_bebe ADD CONSTRAINT FK_D9F229E63689A1A3 FOREIGN KEY (maternite_id) REFERENCES maternite (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE maternite_bebe ADD CONSTRAINT FK_D9F229E6AF762365 FOREIGN KEY (bebe_id) REFERENCES bebe (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medicament_prescrit ADD CONSTRAINT FK_2640BAB993DB413D FOREIGN KEY (prescription_id) REFERENCES prescription_medicaments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE medicament_prescrit ADD CONSTRAINT FK_2640BAB9AB0D61F7 FOREIGN KEY (medicament_id) REFERENCES pharmacie (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prescription_medicaments ADD CONSTRAINT FK_ABFCF59A6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prescription_medicaments ADD CONSTRAINT FK_ABFCF59AD486E642 FOREIGN KEY (prescripteur_id) REFERENCES medecin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE radiologie ADD CONSTRAINT FK_12FB57496B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE radiologie ADD CONSTRAINT FK_12FB574913457256 FOREIGN KEY (technicien_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A4F31A84 FOREIGN KEY (medecin_id) REFERENCES medecin (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE urgence ADD CONSTRAINT FK_737D6BCD6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bebe DROP CONSTRAINT FK_946475AD39DEC40E');
        $this->addSql('ALTER TABLE biologie DROP CONSTRAINT FK_EB9829936B899279');
        $this->addSql('ALTER TABLE biologie DROP CONSTRAINT FK_EB98299313457256');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A66B899279');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A64F31A84');
        $this->addSql('ALTER TABLE gynecologie DROP CONSTRAINT FK_AC9A669E6B899279');
        $this->addSql('ALTER TABLE hospitalisation DROP CONSTRAINT FK_67C059596B899279');
        $this->addSql('ALTER TABLE maternite DROP CONSTRAINT FK_7E1C52BC39DEC40E');
        $this->addSql('ALTER TABLE maternite_bebe DROP CONSTRAINT FK_D9F229E63689A1A3');
        $this->addSql('ALTER TABLE maternite_bebe DROP CONSTRAINT FK_D9F229E6AF762365');
        $this->addSql('ALTER TABLE medicament_prescrit DROP CONSTRAINT FK_2640BAB993DB413D');
        $this->addSql('ALTER TABLE medicament_prescrit DROP CONSTRAINT FK_2640BAB9AB0D61F7');
        $this->addSql('ALTER TABLE prescription_medicaments DROP CONSTRAINT FK_ABFCF59A6B899279');
        $this->addSql('ALTER TABLE prescription_medicaments DROP CONSTRAINT FK_ABFCF59AD486E642');
        $this->addSql('ALTER TABLE radiologie DROP CONSTRAINT FK_12FB57496B899279');
        $this->addSql('ALTER TABLE radiologie DROP CONSTRAINT FK_12FB574913457256');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A6B899279');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A4F31A84');
        $this->addSql('ALTER TABLE urgence DROP CONSTRAINT FK_737D6BCD6B899279');
        $this->addSql('DROP TABLE bebe');
        $this->addSql('DROP TABLE biologie');
        $this->addSql('DROP TABLE consultation');
        $this->addSql('DROP TABLE gynecologie');
        $this->addSql('DROP TABLE hospitalisation');
        $this->addSql('DROP TABLE maternite');
        $this->addSql('DROP TABLE maternite_bebe');
        $this->addSql('DROP TABLE medecin');
        $this->addSql('DROP TABLE medicament_prescrit');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE pharmacie');
        $this->addSql('DROP TABLE prescription_medicaments');
        $this->addSql('DROP TABLE radiologie');
        $this->addSql('DROP TABLE rendez_vous');
        $this->addSql('DROP TABLE urgence');
        $this->addSql('DROP TABLE "user"');
    }
}
