<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250120113911 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE biologie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_examen VARCHAR(100) NOT NULL, resultat TEXT DEFAULT NULL, date_examen TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commentaires TEXT DEFAULT NULL, statut VARCHAR(100) NOT NULL, patient_id INT NOT NULL, technicien_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EB9829936B899279 ON biologie (patient_id)');
        $this->addSql('CREATE INDEX IDX_EB98299313457256 ON biologie (technicien_id)');
        $this->addSql('CREATE TABLE bloc_operatoire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_bloc VARCHAR(20) NOT NULL, statut VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE chirurgie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_chirurgie VARCHAR(100) NOT NULL, heure_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, heure_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, patient_id INT NOT NULL, chirurgien_id INT NOT NULL, bloc_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EC5628096B899279 ON chirurgie (patient_id)');
        $this->addSql('CREATE INDEX IDX_EC5628096DB64F5D ON chirurgie (chirurgien_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EC5628095582E9C0 ON chirurgie (bloc_id)');
        $this->addSql('CREATE TABLE gynecologie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_consultation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, diagnostic TEXT NOT NULL, plan_traitement TEXT DEFAULT NULL, date_suivi TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patient_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AC9A669E6B899279 ON gynecologie (patient_id)');
        $this->addSql('CREATE TABLE maternite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_accouchement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type_accouchement VARCHAR(255) NOT NULL, notes TEXT DEFAULT NULL, mere_id INT NOT NULL, bebe_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7E1C52BC39DEC40E ON maternite (mere_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7E1C52BCAF762365 ON maternite (bebe_id)');
        $this->addSql('CREATE TABLE pharmacie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, medicament VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, stock INT NOT NULL, date_peremption DATE NOT NULL, numero_lot VARCHAR(255) DEFAULT NULL, emplacement VARCHAR(150) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE prescription_medicaments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dose VARCHAR(100) NOT NULL, frequence VARCHAR(255) NOT NULL, date_prescription DATE NOT NULL, patient_id INT NOT NULL, medicament_id INT NOT NULL, prescripteur_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ABFCF59A6B899279 ON prescription_medicaments (patient_id)');
        $this->addSql('CREATE INDEX IDX_ABFCF59AAB0D61F7 ON prescription_medicaments (medicament_id)');
        $this->addSql('CREATE INDEX IDX_ABFCF59AD486E642 ON prescription_medicaments (prescripteur_id)');
        $this->addSql('CREATE TABLE radiologie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_examen VARCHAR(255) NOT NULL, date_examen TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resultat TEXT DEFAULT NULL, images TEXT DEFAULT NULL, patient_id INT NOT NULL, technicien_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_12FB57496B899279 ON radiologie (patient_id)');
        $this->addSql('CREATE INDEX IDX_12FB574913457256 ON radiologie (technicien_id)');
        $this->addSql('CREATE TABLE urgence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, patient_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_737D6BCD6B899279 ON urgence (patient_id)');
        $this->addSql('ALTER TABLE biologie ADD CONSTRAINT FK_EB9829936B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE biologie ADD CONSTRAINT FK_EB98299313457256 FOREIGN KEY (technicien_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chirurgie ADD CONSTRAINT FK_EC5628096B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chirurgie ADD CONSTRAINT FK_EC5628096DB64F5D FOREIGN KEY (chirurgien_id) REFERENCES medecin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chirurgie ADD CONSTRAINT FK_EC5628095582E9C0 FOREIGN KEY (bloc_id) REFERENCES bloc_operatoire (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gynecologie ADD CONSTRAINT FK_AC9A669E6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE maternite ADD CONSTRAINT FK_7E1C52BC39DEC40E FOREIGN KEY (mere_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE maternite ADD CONSTRAINT FK_7E1C52BCAF762365 FOREIGN KEY (bebe_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prescription_medicaments ADD CONSTRAINT FK_ABFCF59A6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prescription_medicaments ADD CONSTRAINT FK_ABFCF59AAB0D61F7 FOREIGN KEY (medicament_id) REFERENCES pharmacie (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prescription_medicaments ADD CONSTRAINT FK_ABFCF59AD486E642 FOREIGN KEY (prescripteur_id) REFERENCES medecin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE radiologie ADD CONSTRAINT FK_12FB57496B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE radiologie ADD CONSTRAINT FK_12FB574913457256 FOREIGN KEY (technicien_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE urgence ADD CONSTRAINT FK_737D6BCD6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hospitalisation ALTER date_entree DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE biologie DROP CONSTRAINT FK_EB9829936B899279');
        $this->addSql('ALTER TABLE biologie DROP CONSTRAINT FK_EB98299313457256');
        $this->addSql('ALTER TABLE chirurgie DROP CONSTRAINT FK_EC5628096B899279');
        $this->addSql('ALTER TABLE chirurgie DROP CONSTRAINT FK_EC5628096DB64F5D');
        $this->addSql('ALTER TABLE chirurgie DROP CONSTRAINT FK_EC5628095582E9C0');
        $this->addSql('ALTER TABLE gynecologie DROP CONSTRAINT FK_AC9A669E6B899279');
        $this->addSql('ALTER TABLE maternite DROP CONSTRAINT FK_7E1C52BC39DEC40E');
        $this->addSql('ALTER TABLE maternite DROP CONSTRAINT FK_7E1C52BCAF762365');
        $this->addSql('ALTER TABLE prescription_medicaments DROP CONSTRAINT FK_ABFCF59A6B899279');
        $this->addSql('ALTER TABLE prescription_medicaments DROP CONSTRAINT FK_ABFCF59AAB0D61F7');
        $this->addSql('ALTER TABLE prescription_medicaments DROP CONSTRAINT FK_ABFCF59AD486E642');
        $this->addSql('ALTER TABLE radiologie DROP CONSTRAINT FK_12FB57496B899279');
        $this->addSql('ALTER TABLE radiologie DROP CONSTRAINT FK_12FB574913457256');
        $this->addSql('ALTER TABLE urgence DROP CONSTRAINT FK_737D6BCD6B899279');
        $this->addSql('DROP TABLE biologie');
        $this->addSql('DROP TABLE bloc_operatoire');
        $this->addSql('DROP TABLE chirurgie');
        $this->addSql('DROP TABLE gynecologie');
        $this->addSql('DROP TABLE maternite');
        $this->addSql('DROP TABLE pharmacie');
        $this->addSql('DROP TABLE prescription_medicaments');
        $this->addSql('DROP TABLE radiologie');
        $this->addSql('DROP TABLE urgence');
        $this->addSql('ALTER TABLE hospitalisation ALTER date_entree SET NOT NULL');
    }
}
